### ISSUE TITLE
Error when trying to validate RAPIDS location features

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#206]
### Discussed in https://github.com/carissalow/rapids/discussions/204

<div type='discussions-op-text'>

<sup>Originally posted by **VHolstein** January 16, 2023</sup>
Dear RAPIDS developers,

I have started building my own RAPDIS container for an app that we use. For validation, I would like to compare GPS location features of the Barnett & Doryab pipelines. For testing, I have rearranged the location data into the same format as the aware_csv data. It seems to run fine, but I get this error message: 
`Warning message: The following named parsers don't match the column names: local_date_time, local_start_date_time, local_end_date_time` 

when running the job 
```
rule phone_locations_processed_with_datetime:
    input: data/interim/test1/phone_locations_processed.csv, data/interim/time_segments/test1_time_segments.csv, data/external/participant_files/test1.yaml
    output: data/interim/test1/phone_locations_processed_with_datetime.csv, data/interim/test1/phone_locations_processed_with_datetime.done
```
and the output files are empty. GPS location data seems to look the same as the example csv for aware_csv data. The beginning of my config file is:

```
########################################################################################################################
#                                              GLOBAL CONFIGURATION                                                    #
########################################################################################################################

# See https://www.rapids.science/latest/setup/configuration/#participant-files
PIDS: [test1, test2, test3]

# See https://www.rapids.science/latest/setup/configuration/#automatic-creation-of-participant-files
CREATE_PARTICIPANT_FILES:
  CSV_FILE_PATH: "data/external/ReMAP_test_participants.csv" # see docs for required format
  PHONE_SECTION:
    ADD: True
    IGNORED_DEVICE_IDS: []
  FITBIT_SECTION:
    ADD: False
    IGNORED_DEVICE_IDS: []
  EMPATICA_SECTION:
    ADD: False

# See https://www.rapids.science/latest/setup/configuration/#time-segments
TIME_SEGMENTS: &time_segments
  TYPE: PERIODIC # FREQUENCY, PERIODIC, EVENT
  FILE: "data/external/timesegments_remap.csv"
  INCLUDE_PAST_PERIODIC_SEGMENTS: TRUE # Only relevant if TYPE=PERIODIC, see docs

# See https://www.rapids.science/latest/setup/configuration/#timezone-of-your-study
TIMEZONE:
  TYPE: SINGLE
  SINGLE:
    TZCODE: Europe/Berlin
  MULTIPLE:
    TZCODES_FILE: /spm-data/vault-data4/ReMAP/project_vincent/data/time_segments/multiple_timezones_example.csv
    IF_MISSING_TZCODE: STOP
    DEFAULT_TZCODE: Europe/Berlin
    FITBIT:
      ALLOW_MULTIPLE_TZ_PER_DEVICE: False
      INFER_FROM_SMARTPHONE_TZ: False
```

Would you have an idea where this error might be coming from? I was unable to locate the problem. If needed I can provide my entire config file or any other of the necessary helper files. Thanks a lot in advance!</div>
